language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls

before_script:
  - psql -c 'CREATE DATABASE "ride-my-way";' -U postgres
  - psql ride-my-way \PASSWORD ar15tottle
# command to run tests
script:
  - coverage run -m pytest 
after_success:
  - coveralls

