language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install python-coveralls

# command to run tests
script:
  - pytest 
  - nosetests --with-coverage # Add me to run nose with coverage support.
after_success:
  - coveralls

