language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls

before_script:
  - psql -c 'CREATE DATABASE "ride-my-way";' -U postgres
  - export PGPASSWORD = "ar15tottle"
  - psql -c 'CREATE TABLE rides (id SERIAL PRIMARY KEY, user_id  INT NOT NULL, location VARCHAR NOT NULL, destination VARCHAR NOT NULL, leaving VARCHAR NOT NULL, passengers VARCHAR);' -U postgres
  - psql -c 'CREATE TABLE users (id SERIAL PRIMARY KEY, name varchar NOT NULL, email varchar NOT NULL, password VARCHAR NOT NULL, dl_path varchar, car_reg varchar);' -U postgres
  - psql -c 'CREATE TABLE requests (id SERIAL PRIMARY KEY, ride_id INT NOT NULL, passenger_id INT NOT NULL, pickup VARCHAR NOT NULL, dropoff varchar, status varchar);' -U postgres
  - psql -c 'SELECT * FROM users;' -U postgres
# command to run tests
script:
  - coverage run -m pytest 
after_success:
  - coveralls

